const listProductsDetail = [
    // ! Mô hình Onepiece
    {
        name: "Donquixote Doflamingo",
        discount: "5%",
        image: "./assets/img/product/OP1.png",
        old_price: 50,
        new_price: 40,
        make_country: "China",
        manufacturer: "G5 Studio",
        data_category: "Onepiece",
        id: "OnepieceA",
    },
    {
        name: "Monkey D. Luffy",
        discount: "6%",
        image: "./assets/img/product/OP2.png",
        old_price: 80,
        new_price: 60,
        make_country: "Viet Nam",
        manufacturer: "MegaHouse",
        data_category: "Onepiece",
        id: "OnepieceB",
    },
    {
        name: "Roronoa Zoro",
        discount: "7%",
        image: "./assets/img/product/OP3.png",
        old_price: 70,
        new_price: 50,
        make_country: "Japan",
        manufacturer: "Whoo",
        data_category: "Onepiece",
        id: "OnepieceC",
    },
    {
        name: "Portgas D. Ace",
        discount: "8%",
        image: "./assets/img/product/OP4.png",
        old_price: 50,
        new_price: 40,
        make_country: "England",
        manufacturer: "MRC",
        data_category: "Onepiece",
        id: "OnepieceD",
    },
    {
        name: "Boa Hancock.",
        discount: "9%",
        image: "./assets/img/product/OP5.png",
        old_price: 90,
        new_price: 80,
        make_country: "Russia",
        manufacturer: "Mixed Lot",
        data_category: "Onepiece",
        id: "OnepieceE",
    },

    // ! Mô hình Dragon Ball
    {
        name: "Son Goku",
        discount: "5%",
        image: "./assets/img/product/DB1.png",
        old_price: 51,
        new_price: 41,
        make_country: "China",
        manufacturer: "G5 Studio",
        data_category: "DragonBall",
        id: "DragonBallA",
    },
    {
        name: "Krillin",
        discount: "6%",
        image: "./assets/img/product/DB2.png",
        old_price: 81,
        new_price: 61,
        make_country: "Viet Nam",
        manufacturer: "MegaHouse",
        data_category: "DragonBall",
        id: "DragonBallB",
    },
    {
        name: "Yamcha",
        discount: "7%",
        image: "./assets/img/product/DB3.png",
        old_price: 71,
        new_price: 51,
        make_country: "Japan",
        manufacturer: "Whoo",
        data_category: "DragonBall",
        id: "DragonBallC",
    },
    {
        name: "Trunks",
        discount: "8%",
        image: "./assets/img/product/DB4.png",
        old_price: 51,
        new_price: 41,
        make_country: "England",
        manufacturer: "MRC",
        data_category: "DragonBall",
        id: "DragonBallD",
    },
    {
        name: "Son Goten",
        discount: "9%",
        image: "./assets/img/product/DB5.png",
        old_price: 91,
        new_price: 81,
        make_country: "Russia",
        manufacturer: "Mixed Lot",
        data_category: "DragonBall",
        id: "DragonBallE",
    },

    // ! Mô hình Naruto
    {
        name: "Uchiha Itachi",
        discount: "5%",
        image: "./assets/img/product/N1.png",
        old_price: 52,
        new_price: 42,
        make_country: "China",
        manufacturer: "G5 Studio",
        data_category: "Naruto",
        id: "NarutoA",
    },
    {
        name: "Uchiha Sasuke",
        discount: "6%",
        image: "./assets/img/product/N2.png",
        old_price: 82,
        new_price: 62,
        make_country: "Viet Nam",
        manufacturer: "MegaHouse",
        data_category: "Naruto",
        id: "NarutoB",
    },
    {
        name: "Senju Tobirama",
        discount: "7%",
        image: "./assets/img/product/N3.png",
        old_price: 72,
        new_price: 52,
        make_country: "Japan",
        manufacturer: "Whoo",
        data_category: "Naruto",
        id: "NarutoC",
    },
    {
        name: "Namikaze Minato",
        discount: "8%",
        image: "./assets/img/product/N4.png",
        old_price: 52,
        new_price: 42,
        make_country: "England",
        manufacturer: "MRC",
        data_category: "Naruto",
        id: "NarutoD",
    },
    {
        name: "Senju Hashirma",
        discount: "9%",
        image: "./assets/img/product/N5.png",
        old_price: 92,
        new_price: 82,
        make_country: "Russia",
        manufacturer: "Mixed Lot",
        data_category: "Naruto",
        id: "NarutoE",
    },

    // ! Mô hình  DC
    {
        name: "Wonder Woman",
        discount: "5%",
        image: "./assets/img/product/dc01.png",
        old_price: 53,
        new_price: 43,
        make_country: "China",
        manufacturer: "G5 Studio",
        data_category: "DC",
        id: "DCA",
    },
    {
        name: "Batman",
        discount: "6%",
        image: "./assets/img/product/dc02.png",
        old_price: 83,
        new_price: 63,
        make_country: "Viet Nam",
        manufacturer: "MegaHouse",
        data_category: "DC",
        id: "DCB",
    },
    {
        name: "Watchmen ",
        discount: "7%",
        image: "./assets/img/product/dc03.png",
        old_price: 73,
        new_price: 53,
        make_country: "Japan",
        manufacturer: "Whoo",
        data_category: "DC",
        id: "DCC",
    },
    {
        name: "Flash",
        discount: "8%",
        image: "./assets/img/product/dc04.png",
        old_price: 53,
        new_price: 43,
        make_country: "England",
        manufacturer: "MRC",
        data_category: "DC",
        id: "DCD",
    },
    {
        name: "Superman",
        discount: "9%",
        image: "./assets/img/product/dc05.png",
        old_price: 93,
        new_price: 83,
        make_country: "Russia",
        manufacturer: "Mixed Lot",
        data_category: "DC",
        id: "DCE",
    },

    // ! Mô hình Marvel
    {
        name: "Iron Man",
        discount: "5%",
        image: "./assets/img/product/mv01.png",
        old_price: 54,
        new_price: 44,
        make_country: "China",
        manufacturer: "G5 Studio",
        data_category: "Marvel",
        id: "MarvelA",
    },
    {
        name: "Thor",
        discount: "6%",
        image: "./assets/img/product/mv02.png",
        old_price: 84,
        new_price: 64,
        make_country: "Viet Nam",
        manufacturer: "MegaHouse",
        data_category: "Marvel",
        id: "MarvelB",
    },
    {
        name: " Captain America ",
        discount: "7%",
        image: "./assets/img/product/mv03.png",
        old_price: 74,
        new_price: 54,
        make_country: "Japan",
        manufacturer: "Whoo",
        data_category: "Marvel",
        id: "MarvelC",
    },
    {
        name: "Spider-Man",
        discount: "8%",
        image: "./assets/img/product/mv04.png",
        old_price: 54,
        new_price: 44,
        make_country: "England",
        manufacturer: "MRC",
        data_category: "Marvel",
        id: "MarvelD",
    },
    {
        name: "Hulk",
        discount: "9%",
        image: "./assets/img/product/mv05.png",
        old_price: 94,
        new_price: 84,
        make_country: "Russia",
        manufacturer: "Mixed Lot",
        data_category: "Marvel",
        id: "MarvelE",
    },

    // ! Mô hình  Kiếm Sĩ
    {
        name: "Yoriichi ",
        discount: "5%",
        image: "./assets/img/product/ks01.png",
        old_price: 55,
        new_price: 45,
        make_country: "China",
        manufacturer: "G5 Studio",
        data_category: "Ks",
        id: "KsA",
    },
    {
        name: "Sabito",
        discount: "6%",
        image: "./assets/img/product/ks02.png",
        old_price: 85,
        new_price: 65,
        make_country: "Viet Nam",
        manufacturer: "MegaHouse",
        data_category: "Ks",
        id: "KsB",
    },
    {
        name: "Gyuutarou ",
        discount: "7%",
        image: "./assets/img/product/ks03.png",
        old_price: 75,
        new_price: 55,
        make_country: "Japan",
        manufacturer: "Whoo",
        data_category: "Ks",
        id: "KsC",
    },
    {
        name: "Kokushibou ",
        discount: "8%",
        image: "./assets/img/product/ks04.png",
        old_price: 55,
        new_price: 45,
        make_country: "England",
        manufacturer: "MRC",
        data_category: "Ks",
        id: "KsD",
    },
    {
        name: " Uzui Tengen.",
        discount: "9%",
        image: "./assets/img/product/ks05.png",
        old_price: 95,
        new_price: 85,
        make_country: "Russia",
        manufacturer: "Mixed Lot",
        data_category: "Ks",
        id: "KsE",
    },
    // ! Mô hình  Atack
    {
        name: "Eren Yeager",
        discount: "5%",
        image: "./assets/img/product/at01.png",
        old_price: 56,
        new_price: 46,
        make_country: "China",
        manufacturer: "G5 Studio",
        data_category: "Atack",
        id: "AtackA",
    },
    {
        name: "Erwin Smith",
        discount: "6%",
        image: "./assets/img/product/at02.png",
        old_price: 86,
        new_price: 66,
        make_country: "Viet Nam",
        manufacturer: "MegaHouse",
        data_category: "Atack",
        id: "AtackB",
    },
    {
        name: "Levi ",
        discount: "7%",
        image: "./assets/img/product/at03.png",
        old_price: 76,
        new_price: 56,
        make_country: "Japan",
        manufacturer: "Whoo",
        data_category: "Atack",
        id: "AtackC",
    },
    {
        name: "Annie Leonhart",
        discount: "8%",
        image: "./assets/img/product/at04.png",
        old_price: 56,
        new_price: 46,
        make_country: "England",
        manufacturer: "MRC",
        data_category: "Atack",
        id: "AtackD",
    },
    {
        name: "BERTHOLT HOOVER",
        discount: "9%",
        image: "./assets/img/product/at05.png",
        old_price: 96,
        new_price: 86,
        make_country: "Russia",
        manufacturer: "Mixed Lot",
        data_category: "Atack",
        id: "AtackE",
    },
    // ! Mô hình  Transformers
    {
        name: "Barricade",
        discount: "5%",
        image: "./assets/img/product/tf01.jpg",
        old_price: 57,
        new_price: 47,
        make_country: "China",
        manufacturer: "G5 Studio",
        data_category: "Transformers",
        id: "TransformersA",
    },
    {
        name: "Ironhide",
        discount: "6%",
        image: "./assets/img/product/tf02.jpg",
        old_price: 87,
        new_price: 67,
        make_country: "Viet Nam",
        manufacturer: "MegaHouse",
        data_category: "Transformers",
        id: "TransformersB",
    },
    {
        name: "Optimus Prime ",
        discount: "7%",
        image: "./assets/img/product/tf03.jpg",
        old_price: 77,
        new_price: 57,
        make_country: "Japan",
        manufacturer: "Whoo",
        data_category: "Transformers",
        id: "TransformersC",
    },
    {
        name: "Bumblebee",
        discount: "8%",
        image: "./assets/img/product/tf04.jpg",
        old_price: 57,
        new_price: 47,
        make_country: "England",
        manufacturer: "MRC",
        data_category: "Transformers",
        id: "TransformersD",
    },
    {
        name: "Megatron",
        discount: "9%",
        image: "./assets/img/product/tf05.jpg",
        old_price: 97,
        new_price: 87,
        make_country: "Russia",
        manufacturer: "Mixed Lot",
        data_category: "Transformers",
        id: "TransformersE",
    },
    // ! Mô hình  Chú Thuật
    {
        name: "Itadori Yuji",
        discount: "5%",
        image: "./assets/img/product/ch01.jpg",
        old_price: 58,
        new_price: 48,
        make_country: "China",
        manufacturer: "G5 Studio",
        data_category: "JUJUTSUKAISEN",
        id: "JUJUTSUKAISENA",
    },
    {
        name: "Gojo Satoru",
        discount: "6%",
        image: "./assets/img/product/ch02.jpg",
        old_price: 88,
        new_price: 68,
        make_country: "Viet Nam",
        manufacturer: "MegaHouse",
        data_category: "JUJUTSUKAISEN",
        id: "JUJUTSUKAISENB",
    },
    {
        name: "Sukuna ",
        discount: "7%",
        image: "./assets/img/product/ch03.jpg",
        old_price: 78,
        new_price: 58,
        make_country: "Japan",
        manufacturer: "Whoo",
        data_category: "JUJUTSUKAISEN",
        id: "JUJUTSUKAISENC",
    },
    {
        name: "Geto Suguru",
        discount: "8%",
        image: "./assets/img/product/ch04.jpg",
        old_price: 58,
        new_price: 48,
        make_country: "England",
        manufacturer: "MRC",
        data_category: "JUJUTSUKAISEN",
        id: "JUJUTSUKAISEND",
    },
    {
        name: "Fushiguro Megumi",
        discount: "9%",
        image: "./assets/img/product/ch05.jpg",
        old_price: 98,
        new_price: 88,
        make_country: "Russia",
        manufacturer: "Mixed Lot",
        data_category: "JUJUTSUKAISEN",
        id: "JUJUTSUKAISENE",
    },
];
